server:
  port: 8888
security:
  user:
    password: ${eureka.password:${SECURITY_USER_PASSWORD:password}} # Don't use a default password in a real app
    
    
turbine:
  aggregator:
    clusterConfig: HELLO
  appConfig: hello, echo, reverseproxy
  
  
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}:${random.value}
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka/