server:
  port: 8761
security:
  user:
    password: ${eureka.password:${SECURITY_USER_PASSWORD:password}} # Don't use a default password in a real app

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka/